### ISSUE TITLE
sample script errors

### ISSUE THREAD

**Issue by MareoRaft** [huntzhan/GoogleTranslateAPI#1]
The sample script which you provide on PyPi errors.

Input:

    import google_translate_api as api
    translator = api.TranslateService()
    translator.trans_details('en', 'zh-CN', 'test')
    translator.trans_sentence('en', 'zh-CN', 'test')    
    translator.detect('test')
    
Output:

    ~/Desktop/test % python3 translate.py
    Traceback (most recent call last):
      File "translate.py", line 5, in <module>
        translator.trans_details('en', 'zh-CN', 'test')
      File "/usr/local/lib/python3.5/site-packages/google_translate_api.py", line 329, in trans_details
        return self._translate(src_lang, tgt_lang, src_text)
      File "/usr/local/lib/python3.5/site-packages/google_translate_api.py", line 315, in _translate
        return self._request(src_lang, tgt_lang, src_texts)
      File "/usr/local/lib/python3.5/site-packages/google_translate_api.py", line 210, in _request
        self._check_threads(threads)
      File "/usr/local/lib/python3.5/site-packages/google_translate_api.py", line 97, in _check_threads
        raise future.exception()
      File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/concurrent/futures/thread.py", line 55, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/usr/local/lib/python3.5/site-packages/google_translate_api.py", line 133, in _basic_request
        return response.json()
      File "/usr/local/lib/python3.5/site-packages/requests/models.py", line 812, in json
        return complexjson.loads(self.text, **kwargs)
      File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/__init__.py", line 319, in loads
        return _default_decoder.decode(s)
      File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/decoder.py", line 339, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/decoder.py", line 357, in raw_decode
        raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

This was using Python 3.5.  Is it possible that google no longer supports the translation service in this way?  If so, can you provide a fix or remove the library from PyPi?

**Comment by huntzhan** [comment]
Sorry, this project has been deprecated. Thanks for your suggestion. I've removed it from PyPI.

**Comment by MareoRaft** [comment]
Thank you, sir.  Happy coding!
